name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "30 0 * * *"   # 每天刷新一次
  workflow_dispatch:        # 允许手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: ${{ github.ref_name }}
          UTC_OFFSET: 8
